# 추후 수정 가능
profile: "local_hf"
rag_mode: "local_hf"

llm:
  model_name: "meta-llama/Llama-3-8b-instruct"
  temperature: 0.1
  max_new_tokens: 512
  device: "cuda"

embeddings:
  model_name: "sentence-transformers/all-mpnet-base-v2"
